TRANSACTION_DOMAIN_SEPARATOR: str = "TX"
TRANSACTION_GROUP_DOMAIN_SEPARATOR: str = "TG"
MULTISIG_DOMAIN_SEPARATOR: str = "MultisigAddr"
SIGNATURE_ENCODING_INCR: int = 75
SIGNATURE_BYTE_LENGTH: int = 64
PUBLIC_KEY_BYTE_LENGTH: int = 32
CHECKSUM_BYTE_LENGTH: int = 4
TRANSACTION_ID_LENGTH: int = 52
MAX_TX_GROUP_SIZE: int = 16

PROGRAM_PAGE_SIZE: int = 2048
MAX_EXTRA_PROGRAM_PAGES: int = 3
MAX_GLOBAL_STATE_KEYS: int = 64
MAX_LOCAL_STATE_KEYS: int = 16
MAX_APP_ARGS: int = 16
MAX_ARGS_TOTAL_BYTES: int = 2048
MAX_ACCOUNT_REFERENCES: int = 4
MAX_APP_REFERENCES: int = 8
MAX_ASSET_REFERENCES: int = 8
MAX_BOX_REFERENCES: int = 8
MAX_TOTAL_REFERENCES: int = 8
MAX_ASSET_DECIMALS: int = 19
MAX_ASSET_NAME_LENGTH: int = 32
MAX_ASSET_UNIT_NAME_LENGTH: int = 8
MAX_ASSET_URL_LENGTH: int = 96

ZERO_ADDRESS: str = "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAY5HFKQ"
