TRANSACTION_DOMAIN_SEPARATOR = b"TX"
TRANSACTION_GROUP_DOMAIN_SEPARATOR = b"TG"
SIGNATURE_ENCODING_INCR = 75
HASH_BYTES_LENGTH = 32
PUBLIC_KEY_BYTE_LENGTH = 32
MAX_TRANSACTION_GROUP_SIZE = 16
CHECKSUM_BYTE_LENGTH = 4
ADDRESS_LENGTH = 58
TRANSACTION_ID_LENGTH = 52
ZERO_ADDRESS = "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAY5HFKQ"
LENGTH_ENCODE_BYTE_SIZE = 2
BOOL_TRUE_BYTE = 0x80
BOOL_FALSE_BYTE = 0x00
SIGNATURE_BYTE_LENGTH = 64
EMPTY_SIGNATURE = bytes(SIGNATURE_BYTE_LENGTH)

# Transaction fees and amounts
MICROALGOS_TO_ALGOS_RATIO = 1_000_000
MIN_TXN_FEE = 1000

# Application program size constraints
MAX_EXTRA_PROGRAM_PAGES = 3
PROGRAM_PAGE_SIZE = 2048  # In bytes

# Application reference limits
MAX_APP_ARGS = 16
MAX_ARGS_SIZE = 2048  # Maximum size in bytes of all args combined
MAX_OVERALL_REFERENCES = 8
MAX_ACCOUNT_REFERENCES = 8
MAX_APP_REFERENCES = 8
MAX_ASSET_REFERENCES = 8
MAX_BOX_REFERENCES = 8

# Application state schema limits
MAX_GLOBAL_STATE_KEYS = 64
MAX_LOCAL_STATE_KEYS = 16

# Asset configuration limits
MAX_ASSET_NAME_LENGTH = 32  # In bytes
MAX_ASSET_UNIT_NAME_LENGTH = 8  # In bytes
MAX_ASSET_URL_LENGTH = 96  # In bytes
MAX_ASSET_DECIMALS = 19
