[project]
name = "algokit-transact"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
  "msgpack>=1.0.0,<2",
  "msgpack-types>=0.2.0,<=0.5",
  "typing-extensions>=4.9,<5",
]
