[project]
name = "algokit-transact"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
  "algokit-common>=0.1.0",
  "msgpack>=1.0.0,<2",
  "msgpack-types>=0.2.0,<=0.5",
  "typing-extensions>=4.9,<5",
  "pynacl>=1.4.0,<2",
]

[tool.pytest.ini_options]
pythonpath = ["src"]
testpaths = ["tests"]

[tool.mypy]
python_version = "3.10"
mypy_path = ["src"]
strict_optional = true
warn_redundant_casts = true
warn_unused_ignores = true
no_implicit_optional = true
ignore_missing_imports = true
disable_error_code = ["literal-required", "misc"]

[[tool.mypy.overrides]]
module = ["algokit_common", "algokit_common.*"]
ignore_missing_imports = true
