[project]
name = "algokit-common"
version = "0.1.0"
description = "Common primitives and utilities shared across AlgoKit Python packages"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
  "pycryptodomex>=3.6.0,<4",
]

[tool.pytest.ini_options]
pythonpath = ["src"]
testpaths = ["tests"]


