name: Continuous Delivery of Python package

on:
  push:
    branches:
      - main
      - alpha
    paths-ignore:
      - ".github/**"
  workflow_dispatch:
    inputs:
      production_release:
        description: "Production release?"
        type: boolean
        required: true
        default: true

concurrency: release

permissions:
  contents: write
  packages: read

jobs:
  ci-check-python:
    name: Check Python
    uses: ./.github/workflows/check-python.yaml

  ci-check-docs:
    name: Check Documentation
    uses: ./.github/workflows/check-docs.yaml

  ci-build-python:
    name: Build Python
    uses: ./.github/workflows/build-python.yaml
    needs: [ci-check-python, ci-check-docs]

  release:
    name: Release Library
    needs: ci-build-python
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write

    steps:
      - name: Generate bot token
        uses: actions/create-github-app-token@v1
        id: app_token
        with:
          app-id: ${{ secrets.BOT_ID }}
          private-key: ${{ secrets.BOT_SK }}

      - uses: actions/checkout@v4
        with:
          # Fetch entire repository history so we can determine version number from it
          fetch-depth: 0
          token: ${{ steps.app_token.outputs.token }}

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Install dependencies
        run: uv sync

      - name: Get branch name
        shell: bash
        run: echo "branch=${GITHUB_REF#refs/heads/}" >> $GITHUB_OUTPUT
        id: get_branch

      - name: Set Git user as GitHub actions
        run: git config --global user.email "179917785+engineering-ci[bot]@users.noreply.github.com" && git config --global user.name "engineering-ci[bot]"

      - name: Create Continuous Deployment - Alpha
        id: release-alpha
        if: steps.get_branch.outputs.branch == 'alpha'
        uses: python-semantic-release/python-semantic-release@v10.3.1
        with:
          github_token: ${{ steps.app_token.outputs.token }}
          prerelease: true
          prerelease_token: alpha

      - name: Create Continuous Deployment - Beta (non-prod)
        id: release-beta
        if: steps.get_branch.outputs.branch == 'main' && !inputs.production_release
        uses: python-semantic-release/python-semantic-release@v10.3.1
        with:
          github_token: ${{ steps.app_token.outputs.token }}
          prerelease: true

      - name: Create Continuous Deployment - Production
        id: release-prod
        if: steps.get_branch.outputs.branch == 'main' && inputs.production_release
        uses: python-semantic-release/python-semantic-release@v10.3.1
        with:
          github_token: ${{ steps.app_token.outputs.token }}

      - name: Publish package distributions to PyPI
        if: |
          (steps.release-alpha.outputs.released == 'true') ||
          (steps.release-beta.outputs.released == 'true') ||
          (steps.release-prod.outputs.released == 'true')
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          verbose: true

  deploy-docs:
    name: Deploy Documentation
    needs: ci-build-python
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build documentation
        uses: ./.github/actions/publish-docs

      - name: Upload to GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/dist

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
