name: Check Python Code

on:
  workflow_call:

jobs:
  check-python:
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout source code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Setup Python environment
        uses: algorandfoundation/algokit-shared-config/.github/actions/setup-algokit-python@main
        with:
          python-version: "3.10"
          install-algokit: "false"

      - name: Audit with pip-audit
        run: |
          # audit all dependencies.
          # If a vulnerability is found in a dev dependency without an available fix,
          # it can be temporarily ignored by adding --ignore-vuln e.g.
          # --ignore-vuln "GHSA-hcpj-qp55-gfph" # GitPython vulnerability, dev only dependency
          uv run --no-sync pip-audit

      - name: Check formatting with Ruff
        run: uv run ruff format --check .

      - name: Check linting with Ruff
        run: uv run ruff check .

      - name: Check types with mypy
        run: uv run mypy
